### ISSUE TITLE
System admin screen for regions to tweak ineligibility/rating criteria

### ISSUE THREAD

**Issue by jschnei** [ripgarpr/garpr#104]
Add an interface where admins can manually tweak ineligibility/rating criteria for regions (e.g. how many tournaments in the last how many days necessary to be active, whether to include OOR players when ranking, etc.).

**Comment by BrandonCookeDev** [comment]
Do we need a whole new view for this? It feels like these options can be displayed on the Rankings page.

**Comment by jschnei** [comment]
Yeah, on the ranking page is probably fine. Just a convenient interface somewhere.

**Comment by BrandonCookeDev** [comment]
I'm interested in tweaking criteria for me region, so I can self-assign and look into this.

**Comment by BrandonCookeDev** [comment]
This issue is on hold until #109 is closed

**Comment by BrandonCookeDev** [comment]
This issue is now on hold until PR #113 's merge is determined

**Comment by Jamesargy6** [comment]
As per our discussion in Slack/issue #104, adding a date range as to the breadth of results considered may be helpful for retroactively calculating rankings, and excluding old data.

**Comment by BrandonCookeDev** [comment]
Sure we can definitely add that

**Comment by BrandonCookeDev** [comment]
Fixed by #144
