### ISSUE TITLE
Database Overhaul

### ISSUE THREAD

**Issue by BrandonCookeDev** [ripgarpr/garpr#109]
Currently @jschnei is working on an overhaul to our Database. It is roadblocking some issues that are being worked on. 
Creating an issue to link to in order to track when it's resolved and said issues are no longer roadblocked.

**Comment by jschnei** [comment]
Sorry about the delay on this. This PR is the current state of the database overhaul: https://github.com/ripgarpr/garpr/pull/110 .

Please take a look/give me your opinions. I think this is worth trying to do right the first time, so we don't run into problems like this in the future.

**Comment by jschnei** [comment]
Should be resolved by #113 .
