### ISSUE TITLE
QOL: front-end angular refactor

### ISSUE THREAD

**Issue by Jamesargy6** [ripgarpr/garpr#111]
Currently, all of our angular controllers reside in one ever-growing file (script.js), sharing a directory with all of our view definitions. As the project continues to scale, the current hierarchy will only get more unwieldy. 

I'd like to modularize our front-end code, breaking up the script.js file into separate modules for each screen, containing each screen's controller, view, and any other angular we may have written. Going forward this project structure will be much more sustainable.

**Comment by jschnei** [comment]
+1, definitely could use this
