### ISSUE TITLE
Ability to add "Floating" Sets

### ISSUE THREAD

**Issue by Jamesargy6** [ripgarpr/garpr#114]
Conceptually the opposite of #73 , Implement a way to manually add singular sets from OOR tournaments. Some players criticized the system's inability to consider OOR results of sets between in-region players.

**Comment by BrandonCookeDev** [comment]
@jschnei @jhertz 
Is this a thing? I was under the impression that my results at CEO, even tho it's CFL, affected my overall skill ranking which is how I get ranked.

**Comment by Jamesargy6** [comment]
Closing, this function will be taken care of by @BrandonCookeDev's implementation of #139
