### ISSUE TITLE
Firefox not rendering player search correctly

### ISSUE THREAD

**Issue by Jamesargy6** [ripgarpr/garpr#117]
Some users are complaining that the player search stops working after two characters. Not sure if we've even attempted support for anything besides chrome, but it's worth starting to take a look at.

**Comment by BrandonCookeDev** [comment]
firefox works fine for me

**Comment by Jamesargy6** [comment]
huh, I'll ask for more information.

**Comment by Jamesargy6** [comment]
Couldn't reproduce, closing.

**Comment by BrandonCookeDev** [comment]
I bet they didn't wait long enough for the API to give back the data from the PlayerService.
Granted, it does currently take a while to get the data from the backend to the UI.
