### ISSUE TITLE
Add Eligibility Flag for tournaments

### ISSUE THREAD

**Issue by Jamesargy6** [ripgarpr/garpr#127]
Add a flag in the database which denotes whether the tournament should be counted towards the eligibility criteria for rankings generation. The tournaments' results will still be counted towards the rankings. This way, certain tournaments which don't garner enough entrants don't qualify a player as "active", but their performance still factors into their score. This is also a helpful feature for importing pools, as a pools bracket and pro/am bracket should not count as two separate tournaments from an activity perspective.

**Comment by BrandonCookeDev** [comment]
Doing this one now

**Comment by BrandonCookeDev** [comment]
Fixed by #172
