### ISSUE TITLE
Mobile Site

### ISSUE THREAD

**Issue by Jamesargy6** [ripgarpr/garpr#143]
A lot of our users (myself included) use the website via their phones. As our site is obviously created for desktop users, a lot of the functions we offer are clunky and difficult to use. Having a simple version of the application for mobile would go a long way for a lot of users. I'll update this later with a list of features to include

**Comment by BrandonCookeDev** [comment]
+1
Was going to eventually make an issue about this

**Comment by BrandonCookeDev** [comment]
Should be mostly solved by #164
