### ISSUE TITLE
[Feature] Display the regions that a player is associated with

### ISSUE THREAD

**Issue by jiangtyd** [ripgarpr/garpr#186]
1. User feature: We display all the regions for a player in the pending tournament upload screen, but that's it. A player's page should show what regions they're in.

    a. Should be able to filter tournaments for a player by region?

2. Admin feature: Under "edit player details," there's a checkbox showing which regions in which the player will be included for rankings. I think it only displays checkboxes for regions for which the logged-in user is an admin.

    This is confusing because, for example, player search could show the player as being in one region, and they might only see checkboxes for the user's region.

    To make this less confusing, we could show read-only checkboxes for other regions that the player can be ranked in.

**Comment by BrandonCookeDev** [comment]
This may be a good one for @JarrodBlanton to get his feet wet in the frontend.

**Comment by BrandonCookeDev** [comment]
Fixed by #224
