### ISSUE TITLE
write smashgg importer

### ISSUE THREAD

**Issue by jessemtso** [ripgarpr/garpr#19]
lol "scraper"

**Comment by BrandonCookeDev** [comment]
Created a 'scraper' for smash gg. 

-def get_matches sends back MatchResult model objects as expected

-Also class can populate lists of more detailed SmashGGPlayer and SmashGGMatch objects if so desired. These subclasses aggregate any additional data from the smashgg dump that could prove beneficial in the future. 

Test suite contains two tests for each function. 16 tests in total. May need more tests including functions found in the MatchResult model. 

Creating a PR for this now.

**Comment by jessemtso** [comment]
@BrandonCookeDev reminder, create a PR for this when its ready

**Comment by BrandonCookeDev** [comment]
I was going to ask in slack @jessemtso am I PR into Gar's master or into @yedi 's?

**Comment by jessemtso** [comment]
into yedis. gar’s is over. yedis is the master now

**Comment by BrandonCookeDev** [comment]
Got it, I assumed it was Yedi's so I went ahead and did that. If i was wrong we could fix it later but looks like we're good!

**Comment by jessemtso** [comment]
closed by https://github.com/ripgarpr/garpr/pull/32
