### ISSUE TITLE
setup real deployment process

### ISSUE THREAD

**Issue by jessemtso** [ripgarpr/garpr#24]
assign to jon and yedi

**Comment by jessemtso** [comment]
we should have a deployment process that does things like:

makes sure master passes test suite
pushes it to prod


we should also make sure we're taking lots of DB dumps

**Comment by jessemtso** [comment]
and we should do this kinda soon, so that our ppl can keep adding tournaments

**Comment by jessemtso** [comment]
@yedi give us dem ansible scripts and whatever else we need to understand deploying to prod

**Comment by jessemtso** [comment]
this is p1 for rn

**Comment by jschnei** [comment]
See https://github.com/ripgarpr/garpr/blob/master/jenkins/README.md and the Jenkins server at njssbm.com:8080

**Comment by jschnei** [comment]
Still need to add a cronjob for taking backups... will add new issue.
