### ISSUE TITLE
Confirm Vagrant working on Windows

### ISSUE THREAD

**Issue by acoulon99** [ripgarpr/garpr#33]
Having issues using Vagrant on Windows at the moment. Once debugged and fixed, will update the readme.

**Comment by acoulon99** [comment]
Noting this issue (happend to me on windows 10 just now)
https://github.com/mitchellh/vagrant/issues/7417

**Comment by BrandonCookeDev** [comment]
I get a bunch of SSH issues randomly when after trying to Vagrant Up after Vagrant Suspend'ing the VM. 
If I delete the insecure_private_key that it looks at, then Vagrant Up --> Fail, Vagrant Destroy, then re-Vagrant Up it works, but I still have to wait for it to come back up.

**Comment by BrandonCookeDev** [comment]
@acoulon99 
nosetests runs 0 tests for me. Thoughts?
![nosetests](https://cloud.githubusercontent.com/assets/10892126/16100884/6a532e56-332f-11e6-8db8-382823528d48.PNG)

**Comment by BrandonCookeDev** [comment]
Ok fixed nosetests.
On a Windows box apparently running ```nosetests --exe``` runs the tests correctly.
Something about nosetests suppose to exclude executables. --exe switch includes these in the tests

**Comment by BrandonCookeDev** [comment]
Bash start.sh produces an error for me
![capture](https://cloud.githubusercontent.com/assets/10892126/16115589/f78aa432-3395-11e6-8652-6776e9a6974b.PNG)

@jschnei just made an update to this file but it's probably just Windows. Tagging so maybe he can shed some light on it

**Comment by BrandonCookeDev** [comment]
I'm reloading VirtualBox and starting back on this

**Comment by jessemtso** [comment]
this may never work. possibly flag as wontfix?

**Comment by BrandonCookeDev** [comment]
ok so I forgot to update this issue, but vagrant works for me. 
It seems like I just needed a clean reinstall of VirtualBox. 

Should be able to close.
