### ISSUE TITLE
Implement SmashGG Error Handling

### ISSUE THREAD

**Issue by BrandonCookeDev** [ripgarpr/garpr#37]
Due to the recent discovery of instability in the SmashGG api (likely due to new releases), the SmashGG importer module needs better error handling in case updates like these will continue to be an issue.

**Comment by BrandonCookeDev** [comment]
@jessemtso Added an important try catch in the SmashGG branch if you are able to quick-merge without a huge PR.

**Comment by jhertz** [comment]
Open a PR please

**Comment by jessemtso** [comment]
fixed w/ https://github.com/ripgarpr/garpr/commit/16993eefa4ea20ce8f2d3067d7a397d3fe499167
