### ISSUE TITLE
Properly get date of results / allow admins to change date/time of results 

### ISSUE THREAD

**Issue by VestboyMyst** [ripgarpr/garpr#4]
currently garpr uses the date the bracket was created on challonge instead of the date the event was run (which is an optional field in challonge). we need a way for this to be the first field checked, and it would be nice if admins could change the date/time of results so that they count in the right order

two current issues in NJ
-if someone goes back to recreate pools for an event (TCNJ Barkada) the pools are counted months after the event happened.
-if two locals happen in the same day (jersey japes, knight slash)  there is a chance the one that happened 2nd is calculated first if time isnt specified on both of them

**Comment by jessemtso** [comment]
there's code already <https://github.com/yedi/garpr/blob/master/server.py#L457> to handle updating the date of a tournament, this just needs to have UI added for it

**Comment by jessemtso** [comment]
@Jdtanacredi this can be done now if you have time

**Comment by Jdtanacredi** [comment]
Going to be busy w/ freelance until mid July. I'll see if I can find some time to squeeze this in if it's still open.

**Comment by jschnei** [comment]
Closed by #64.
