### ISSUE TITLE
write frontend for smashgg importer

### ISSUE THREAD

**Issue by jhertz** [ripgarpr/garpr#54]
serverside stuff is there now, just need to modify frontend a bit

**Comment by jhertz** [comment]
can either of you guys do it?

**Comment by jessemtso** [comment]
you can see the relevant addition to the code here: https://github.com/ripgarpr/garpr/blob/master/server.py#L403

it's the same basic POST as for a challonge scraper, where type needs to be 'smashgg' and then 'data' is the bracket URL

**Comment by jschnei** [comment]
See #57 .

**Comment by jhertz** [comment]
closed 👍
