### ISSUE TITLE
issue merging players on notgarpr.com

### ISSUE THREAD

**Issue by VestboyMyst** [ripgarpr/garpr#58]
currently when i try to merge players i get the confirmation that the two have been merged, but nothing happens. i can do it over and over and get the same result

**Comment by jschnei** [comment]
Has merging players worked previously?

It looks like right now "merging" two players just adds a merge to a list of pending merges, but these pending merges are never actually merged.

**Comment by jhertz** [comment]
We previously wanted a sysadmin to do the merge, since theyre really hard to undo. 

Maybe now we should let siteadmins do it, and just take a backup beforehand

**Comment by jschnei** [comment]
We could just make merges undoable? This involves storing some extra stuff, but isn't so bad.

**Comment by jhertz** [comment]
Sure. That seems smart

**Comment by VestboyMyst** [comment]
they worked a few weeks ago on njssbm.com

after putting their name in the box and clicking merge, the same confirmation would pop up, and on refresh that page would be blank

undoing is easier now that we can delete brackets at least

**Comment by jhertz** [comment]
i'm not sure it ever "worked a few weeks ago". the merge resource just stores a pending merge. we could add a new page to let region-admins approve their merges i suppose.

also do what @jschnei  said and store some data so they're undoable

https://github.com/ripgarpr/garpr/blob/master/server.py#L857 is where logic would go. GET to list the pending merges, and then we should add a PUT handler to actually 'commit' the merge

**Comment by VestboyMyst** [comment]
not sure when they worked, but at some point on njssbm.com they were working

**Comment by jschnei** [comment]
Should be resolved by #71 .
