### ISSUE TITLE
request: things to improve deleting duplicate players

### ISSUE THREAD

**Issue by VestboyMyst** [ripgarpr/garpr#76]
some combination or variation of these

1) if a bracket is deleted and it is a player's only result, can we automatically delete that player from the system?
2) can we run a script that deletes players with no sets in their profile every week?
3) a delete button that is only allowed to be used by an admin if the player profile has no sets / entries

**Comment by jschnei** [comment]
choice 2 above is implemented now as a side effect of validate_db.py. (tournament-less players should be deleted daily).
