### ISSUE TITLE
feature: admin panel where we can play with trueskill parmeters

### ISSUE THREAD

**Issue by VestboyMyst** [ripgarpr/garpr#81]
somewhere (maybe in the tournaments tab) have a little area with the relevant values we can tweak for trueskill's algorithm

have a field for each where we can enter new ones and maybe its a good idea to have the default values written beside them 

also in this area we can have the "X brackets in last Y days" fields for the admin to edit

**Comment by BrandonCookeDev** [comment]
is this and #104 identical issues?

**Comment by BrandonCookeDev** [comment]
I'm going to close this and refer it to #104 which is identical. If it's not identical let me know and I'll open it again.
