### ISSUE TITLE
Smashgg importer is including amateur brackets if they happen to be in the event

### ISSUE THREAD

**Issue by VestboyMyst** [ripgarpr/garpr#82]
this can be seen with Nebs prime 47 which is one of the few ones the amateur bracket is in the smashgg event and not separate on challonge

https://www.notgarpr.com/#/newjersey/tournaments/577d1f4ae592571213091dc8
https://smash.gg/tournament/nebulous-prime-melee-47/brackets

amateur sets are included in our imported version

maybe we need a new feature for the smashgg uploader, where it shows which individual brackets are in that smashgg event and the admin can check off which ones we want to import / consolidate into one bracket

**Comment by BrandonCookeDev** [comment]
siq.
This one might be a pain. I'll look into it

**Comment by BrandonCookeDev** [comment]
Question: is it necessary to disclude Amateur brackets tho? what's wrong with giving amateurs a part in the relative rankings? it would give regions a big-picture overview of all their players, a feature I know SleepyK and the rest of our region was interested in

**Comment by VestboyMyst** [comment]
i'd say if we include it at all it has to be its own separate bracket so they can be omitted from rankings separately from the main bracket, not mixed in

people express concern about this often, i had 2 reach out within the last few days about wrongfully added amateur sets of theirs. usually its something like 'i left right after i lost pools so those losses shouldnt count' or 'i started sandbagging with low tiers'

personally i dont think they should be added since its clear that effort drops off for most of the players once they dont make it into top bracket

**Comment by BrandonCookeDev** [comment]
hmm, well 'i started sandbagging with low tiers' is totally not a legitimate John, and 'i left right after i lost pools...' would be DQ's which the importer now handle

However I see your point. Anyone that isn't making top bracket may not even deserve to be ranked yet. 
In that case the GUI fix may have to be implemented, but there's a problem even in that.

The API doesn't send us bracket names. We only have event and group id's to identify brackets. If you wanted a clean and fool-proof UI, we would need to attain the bracket names so the TO's would know exactly which one to disqualify.
The most simple way I see us doing this is to actually scrape the HTML from the main page:
#### EXAMPLE:
https://smash.gg/tournament/ceo-2016/brackets
- Find tag for Melee Singles
- Scrape bracket name
- Scrape "View X" Button for its href --> Get the phase-group ids

We can use the above method to map phase-groups to bracket titles, and this way we can display that information to the user.

**Comment by BrandonCookeDev** [comment]
So @jhertz believes the above method should work. At least until SmashGG decides to send us the bracket names. 
I will work on this

**Comment by BrandonCookeDev** [comment]
@jhertz @jschnei @VestboyMyst 

Name is now present in the api. See {entity.event.name} property: 
https://api.smash.gg/event/11218?expand[0]=groups

Question tho. Are these names static or can I like name a bracket mlg420noscopesxxxwavedash or something dumb?
If static we can filter on the backend but if we can do custom like above then we should go with the GUI fix.

**Comment by BrandonCookeDev** [comment]
#86 added api code to return a map of bracket names to their phase id's.
The frontend now needs to call this method and handle it accordingly. This would likely involve checkboxes where anything not checked should be sent to the api for non-inclusion

**Comment by jessemtso** [comment]
@BrandonCookeDev can we close this? or is more work needed?

**Comment by BrandonCookeDev** [comment]
This is handled by PR #91 
Needs to be merged before this is closed.

**Comment by BrandonCookeDev** [comment]
This issue should be closed
