### ISSUE TITLE
Interested getting GARPR setup for my region, not sure how to contact devs...

### ISSUE THREAD

**Issue by MrMonacle** [ripgarpr/garpr#90]
Sorry if this is the wrong avenue to contact you guys, but I want to get it setup. I have a VPS that I can run it on because I was trying to run the old version of GarPR before I found this one.

**Comment by jschnei** [comment]
Yeah,  we can help you either to set it up on your server or to add your region to notgarpr.con.

Most of our communication is done on our slack channel. If you send me your email (either here or to jschneider2013@gmail.com) I'll add you to it.
