### ISSUE TITLE
Should we remove the admin_regions property?

### ISSUE THREAD

**Issue by jschnei** [ripgarpr/garpr#98]
Currently all admin users have a list of "admin_regions", regions which they can administrate. Admins can generally only edit player/tournament information for players/tournaments who belong to regions in their "admin_regions" list. This property is intended to prevent admins for one region (e.g. California) from making unwanted/unintended edits to tournaments/players in another region (e.g. NYC). 

Unfortunately, in practice, there are various issues with this system, including:
1. More complex authorization code everywhere. There have already been a bunch of bugs stemming from this (also some annoying quality-of-life things like #96). 
2. Many players don't belong to one of the established regions (e.g. Wizzrobe comes to a tri-state tourney), but admins still need to edit details of these players. 
   3 (this is a big one). It's currently trivial to get around the limitations of the "admin_regions" property and edit the properties of any tournament/player, simply by first adding them to your region, changing whatever you want, and then removing them from your region. It's not clear what a good fix for this would be; if you prevent admins from adding players to their region, then this makes a variety of admin tasks (including dealing with things like point 2 above) much harder.

Here are some potential solutions to these issues:
1. Remove admin_regions entirely (so any admin can edit any player/tournament). Partially remedy the problem of accountability by logging what edits are made by which admins. This is my preferred solution (I think it is fine given that i. we don't have too many admins, ii. we trust them). 
2. Figure out a consistent semantic meaning of admin_regions (that doesn't have the pitfalls of item 3 above). Not sure what this would look like.
3. Keep admin_regions super strict (in particular, make it so that you can't add other players to your region), but make some superadmin accounts that can do everything. I feel like all our current admins should basically be superadmins, but maybe in the long run this makes sense (not being able to add players to your region is definitely pretty annoying as an admin though).

Thoughts welcome!

**Comment by BrandonCookeDev** [comment]
I believe we agreed upon a super admin position being instated. This allows more of a least-privilege architecture that limits damage in the case of an insider

**Comment by jschnei** [comment]
I think this is essentially closed with our decision to implement both super admins and regional admins.
