### ISSUE TITLE
Add a web interface for creating new regions/new users

### ISSUE THREAD

**Issue by jschnei** [ripgarpr/garpr#99]
Currently, new regions are created manually in mongo and new admin users are created by running [this script](https://github.com/ripgarpr/garpr/blob/master/scripts/create_user.py). Both require access to the server (and somewhat insecurely, people need to tell me what they want their username/pw to be over slack).

The volume of requests for new regions/new users is getting to the point where it is probably worth having a web interface that people could use to generate them (probably this interface should be restricted to some sort of superadmin account). Alternately, a Slack webhook could also work.

**Comment by BrandonCookeDev** [comment]
I'm currently writing up the html and js for this.

**Comment by BrandonCookeDev** [comment]
Basic portal is complete. PR #105

**Comment by BrandonCookeDev** [comment]
This issue is on hold until #109 is closed

**Comment by BrandonCookeDev** [comment]
This issue is now on hold until PR #113 's merge is determined

**Comment by BrandonCookeDev** [comment]
PR #113 was merged.
Now issue is on hold until #118 is completed

**Comment by BrandonCookeDev** [comment]
Fixed by #105
